/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package com.jacoco.aggregate.reports.app

import com.jacoco.aggregate.reports.app.utils.MessageUtils
import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class MessageUtilsTest {
    @Test fun testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage())
    }
}
